### ISSUE TITLE
你好可以问一下如何获取region的id吗

### ISSUE THREAD

**Issue by jiasswee** [Nanomoa/LoveSportAuto#1]
我们学校似乎用的也是一样的校园跑软件

**Comment by Nanomoa** [comment]
> 我们学校似乎用的也是一样的校园跑软件

我们是学校自己开发的**软件，这脚本现在我们校内也不能用了，他重构了

**Comment by jiasswee** [comment]
那寄了（） 我是通过搜aitiyuplus.cn 这个域名找到仓库的，我们学校的软件我通过小黄鸟抓包发现是post一些参数到这个域名来完成运动上报的，感觉这个脚本似乎可以用（）



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年12月03日 16:45 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Nanomoa/LoveSportAuto] 你好可以问一下如何获取region的id吗 (Issue #1) |

我们学校似乎用的也是一样的校园跑软件

我们是学校自己开发的**软件，这脚本现在我们校内也不能用了，他重构了

**Comment by Nanomoa** [comment]
> 那寄了（） 我是通过搜aitiyuplus.cn 这个域名找到仓库的，我们学校的软件我通过小黄鸟抓包发现是post一些参数到这个域名来完成运动上报的，感觉这个脚本似乎可以用（）
> 
> 
> 
> ---- 回复的原邮件 ----
> | 发件人 | ***@***.***> |
> | 日期 | 2024年12月03日 16:45 |
> | 收件人 | ***@***.***> |
> | 抄送至 | ***@***.***>***@***.***> |
> | 主题 | Re: [Nanomoa/LoveSportAuto] 你好可以问一下如何获取region的id吗 (Issue #1) |
> 
> 我们学校似乎用的也是一样的校园跑软件
> 
> 我们是学校自己开发的**软件，这脚本现在我们校内也不能用了，他重构了
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***>

艹，，，，给个联系方式我加你说吧，issue不方便

**Comment by jiasswee** [comment]
企鹅2830017365



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年12月03日 16:51 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Nanomoa/LoveSportAuto] 你好可以问一下如何获取region的id吗 (Issue #1) |

那寄了（） 我是通过搜aitiyuplus.cn 这个域名找到仓库的，我们学校的软件我通过小黄鸟抓包发现是post一些参数到这个域名来完成运动上报的，感觉这个脚本似乎可以用（）

---- 回复的原邮件 ----
| 发件人 | @.> |
| 日期 | 2024年12月03日 16:45 |
| 收件人 | @.> |
| 抄送至 | @.>@.> |
| 主题 | Re: [Nanomoa/LoveSportAuto] 你好可以问一下如何获取region的id吗 (Issue #1) |

我们学校似乎用的也是一样的校园跑软件

我们是学校自己开发的**软件，这脚本现在我们校内也不能用了，他重构了

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: @.***>

艹，，，，给个联系方式我加你说吧，issue不方便
